### ISSUE TITLE
Potential consequences of updating Roundhouse.ScriptsRun

### ISSUE THREAD

**Issue by jkodroff** [chucknorris/roundhouse#250]
Ok, so let me start off with this: I know this is ugly, but I believe I have no choice.

I have to change an entry in Roundhouse.ScriptsRun table for an ordered script.  We were slowly rolling Roundhouse through our environments and when we got to production, we realized that an ordered script contains sysadmin-level statements which cannot be run in by RH our production environment due to security policies outside of my control.  Therefore, I had to remove those statements from the ordered script.

Now I have to ensure that in doing so, I don't break RH on the environments to which it has already been deployed.  That means that I have to trick RH into thinking the new version of the ordered script was the one that actually ran in the non-prod environments.  I plan to do this with the following query:

```sql
update roundhouse.scriptsrun set 
  text_hash = 'hF53daviTpi5bksyOksZnw=='
where text_hash = 'A0NJqYXjjEQ6/QuHvxssrw=='
```

It appears to work.  

Here's my questions:

1. Is it cool to skip updating `text_of_script`?  (Alternatively I might change `text_of_script` to be something like 'THIS WAS HACKED SEE LINE 123 OF FOO.whatever`.)
1. Any other potentially adverse consequences of doing this that I might not be aware of?

**Comment by ferventcoder** [comment]
@jkodroff So we will break this down into a couple of categories, facts, opinions and recommendations.

## Facts
The hash is all that is checked. Most of the other fields are used for auditing, like when SOx-type auditing occurs. Since most folks are only going to care about production, you should be fine.

## Opinions
So here's my opinion on this. Take it for what you will. Once you hit production, you should flip all of your other environments to restore from a production backup (scrubbed, pared down if necessary). This is **the *best* way** to do brownfield development with RoundhousE.  Because the changes really only count in production, just continually play them against the backup of the thing that matters in all of your other environments.

This leads to my recommendation of RestoreRun mode.

## Recommendations

https://github.com/chucknorris/roundhouse/wiki/RoundhousEModes#development-qa-and-staging-deployments

> You will want to fully exercise your database deployment process through development, QA and staging. By the time you've made it through the deployment pipeline, you want to be confident that your scripts will work correctly against the database version ***already in production***. The best way to accomplish this is running RoundhousE in RestoreRun mode.

For local development, I always recommend a local database that is sandboxed per developer. Then adding in RefreshDatabase to your solution so you pretty much automate getting and keeping that DB synced up - https://github.com/chucknorris/roundhouse/wiki/RefreshDatabase. Local integration for the win!

**Comment by jkodroff** [comment]
It's worth noting for laughs that our SQL scripts are templated per-tenant (don't ask - wasn't my idea), so I need to put this hack in a for-each loop after determining all the before and after hashes for our 30 tenants.

Tomorrow is gonna be a fun day at work.
