### ISSUE TITLE
Remove .NET 3.5 Dependency 

### ISSUE THREAD

**Issue by motowilliams** [chucknorris/roundhouse#263]
New deployment machine with only .NETFx 4.6.2 and noticed that are migrations where not running. After debugging and eventually reading the docs we discovered this legacy dependency.

What are the plans for this?

**Comment by erikbra** [comment]
Are there any reasons not to update the whole build environment, @ferventcoder  or @BiggerNoise ? Or am I being a bit trigger-happy? I was thinking upgrading to .NET 4.x (latest), C#7, upgrading some ancient nuget packages, etc?

**Comment by ferventcoder** [comment]
.NET 3.5 is what is std on Windows 2008/R2 and while we can support .NET 4.x easily with an additional config file, you can't go the opposite way easily.

**Comment by erikbra** [comment]
Yes, you are correct. I was sure support had ended for .NET 3.5SP1, but apparently is hasn't: https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework

I was just feeling the "oldness" of some of the tooling and features when doing the unit test framework conversions. And, if one were to hope for more active developers of RoundhousE (which is an excellent tool, I must say), being able to use modern tooling would be an advantage, imho.

I also have feelings for UppercuT/NAnt, etc, but it might be because I'm not used to using them, not because the tools themselves are bad :) I'm just thinking in terms of feedback on failing teamcity builds, etc. But maybe this should be a separate issue.

**Comment by BiggerNoise** [comment]
I am going to be posting a couple of survey type issues to help us get a pulse on how people are using RoundhousE in 2017, I hope that those will help guide us.

That said, my personal inclination is to move to at least .NET 4, but preferably 4.5.

There will be at least one more release with the older framework (0.8.8) that will incorporate many of the P/R's that we have accumulated over the last few years. If we bump versions after that, the folks left behind will at least have an up to date version of RH to work with.

**Comment by erikbra** [comment]
Just a note on this, running on Windows 2016 server, .NET 3.5 is not installed by default. So having a dependency on .NET 3.5 will be a bigger problem than 4.x going forward, imho. Running a standard build of rh.exe on our build server, gives me this:

![image](https://user-images.githubusercontent.com/1628994/31491282-1c1640d0-af47-11e7-88aa-aabc6f914f31.png)

**Comment by BiggerNoise** [comment]
Understood. I want to get 0.8.8 out the door and then I'm going to start modernizing our dependencies.

**Comment by erikbra** [comment]
Lovely. I'll be happy to help if you want. Have quite some experience with setting up build pipelines. Are you planning on migrating to MSBuild?

**Comment by BiggerNoise** [comment]
TBH, at the moment, I'm more concerned with libraries and languages: .NET 4.6, C#7, etc. Let's revisit this when all that is in the can.

**Comment by erikbra** [comment]
True, true. Let's get 0.8.8 out, then we can discuss what adjustments
should be made (if you're interested in collaboration)

12. okt. 2017 15:49 skrev "Andy Davis" <notifications@github.com>:

TBH, at the moment, I'm more concerned with libraries and languages: .NET
4.6, C#7, etc. Let's revisit this when all that is in the can.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/chucknorris/roundhouse/issues/263#issuecomment-336142824>,
or mute the thread

**Comment by erikbra** [comment]
#285 should solve this, I hope.

**Comment by BiggerNoise** [comment]
#285 is merged and addresses this issue.
