### ISSUE TITLE
Why does RoundhousE use sys schema on MySQL?

### ISSUE THREAD

**Issue by macfarmw** [chucknorris/roundhouse#311]
We got RoundhouseE working recently for a new project on MySQL. I noticed that the tracking tables were added to the sys schema. In SQL Server we see a RoundhousE schema for these tables. What is the reason for this difference?

Thanks

**Comment by BiggerNoise** [comment]
I don't know and I don't know if it was intentional or not. The difference does seem a bit odd.

It may have slipped in when I was merging all those P/Rs last year. IIRC, there was a P/R that added schema support for MySQL. It may have just been implemented to use that schema. 

I'll take a look at the migrator for MySQL and the commit history and see if a rationale was buried somewhere in the midst.

**Comment by macfarmw** [comment]
I figured out what's going on and Roundhouse is working correctly.

The connection string we are using includes the Database=SYS. The scripts affect objects in various MySql databases on the same instance so I guess they were trying to avoid breaking the scripts up into folders for each database. Had we split the scripts up into folders and then specified each database separately in multiple calls to RH.exe then I the tracking tables would have been created and maintained inside each database just like in SQL server.

The only difference being that in MySql each database is a schema so the tables are prefixed with roundhouse_ to keep them separated from the application's tables.

**Comment by BiggerNoise** [comment]
Thanks for running this down. 

I was going to look this weekend but had work production stuff to work through and got caught up in Saturday's NPM tantrum. Come Sunday, I didn't want to even look at a computer.
