### ISSUE TITLE
Problem with PostgreSQL database

### ISSUE THREAD

**Issue by Norbus** [chucknorris/roundhouse#312]
Hello, 

I'm getting following error while I'm trying to use roundhouse with PostgreSQL database:

![image](https://user-images.githubusercontent.com/2494088/36369829-0c120972-155d-11e8-8173-6c5dde407256.png)

Could you please help me with this? While I'm downloading the source code from roundhouse repo everything works fine, but when I'm trying to use Nuget packages I'm getting exception from attached screenshot. I saw that you were fixing some problem with connection factoring but I'm not sure if this fix were included in the latest release.

I have also attached im my app config DbProviderFactories for PostgreSQL:

![image](https://user-images.githubusercontent.com/2494088/36369933-64e82f72-155d-11e8-9ede-905b4e0e5b8f.png)

**Comment by Norbus** [comment]
In my opinion there is problem with ILMerge tool. After merging the problem appears.

**Comment by ferventcoder** [comment]
@Norbus that's likely.

**Comment by BiggerNoise** [comment]
First. thank you for reporting the issue and your patience while we fix it. 

FWIW, the latest version of RH does work correctly from the command line:

```
PS C:\development\Chuck\roundhousE\my-repo\db\PostgreSQL\TestRoundhousE> rh.exe --dt postgres --cs "host=localhost;database=moofy;username=postgres;password=xxxxxxxx"
Running RoundhousE v0.9.1.0 against  - moofy.
Looking in . for scripts to run.
Please press enter when ready to kick...

==================================================
Setup, Backup, Create/Restore/Drop
==================================================

<snip>
```

I'm guessing the issue stems from your using RH as a library, and our library not being all there.

If that's the case, could you create a small project that demonstrates the issue? I've never used RH that way and really don't know where to start. Just set it up so that it can connect to a localhost PG and then point me to it.

Thanks

**Comment by Norbus** [comment]
Yep, you are right, I am using RH as a library in a .NET Console Application project. I'll try to upload some sample project as soon as possible.

Additionally I am experiencing one more issue, while I'm passing DB name to RH written with capital letters it creates DB written with small letter and then it causes problem with find that DB during execution the script beause there occurs an error: Database does not exists.

**Comment by BiggerNoise** [comment]
Thanks. It's probably something fairly simple with the ILMerge, but at least with a sample, I can spend my time working the problem instead of chasing my tail with Postgres.

Can you create a separate issue for the lowercasing the database name? I'd be surprised if that had anything to do with the ILMerge. Also, please indicate if this is new behavior.

**Comment by BiggerNoise** [comment]
@Norbus - Sorry, I have been wrapped up on a few other things and haven't had a chance to follow up with you. 

Can you create a simple project that demonstrates the issue? As I said, I think it will be pretty easy to address, I just want to spend my time working on the problem.

**Comment by erikbra** [comment]
Note to self: This wil probably be solved if changing from ILMerge to Fody.Costura on the RoundhousE lib too. Fix for 1.0.v.

**Comment by erikbra** [comment]
Moved this to 1.1.0. Cannot use Fody.Costura on a library, only an executable (the entry assembly

**Comment by erikbra** [comment]
@Norbus is this still an issue if using the latest 1.1.0 release of RoundhousE?

**Comment by erikbra** [comment]
@Norbus do you have any further comments here? If not, I'm closing the issue

**Comment by Norbus** [comment]
Hey @erikbra! You can close this issue.

**Comment by erikbra** [comment]
Thanks. Done :)
